
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class Bouquet extends javax.swing.JFrame {

    /**
     * Creates new form Bouquet
     */
    public static int bcount=0;
    static int tick1;
    static int tick2;
    static int tick3;
    static int tick4;
    static int tick5;
    public Bouquet() {
        //this.setUndecorated(true); //removes the title bar
        //this.setAlwaysOnTop(true); //this interface is always on top
        //this.setResizable(false); //not resizeable now
        //this.setVisible(true);
        initComponents();
       // Toolkit tk = Toolkit.getDefaultToolkit();
          // int xsize = (int) tk.getScreenSize().getWidth();
           //int ysize = (int) tk.getScreenSize().getHeight();
        //this.setSize(xsize, ysize);
        //varInit();
        //JOptionPane.showMessageDialog(null, tick1);
        if(tick1 == 1)
        {
            
            fblossom.setSelected(true);
        }
        
      
        if(tick2 == 1)
        {
            
            fhydrangea.setSelected(true);
        }
                
        if(tick3 == 1)
        {
            
            frose.setSelected(true);
        }  
        
        if(tick4 == 1)
        {
            
            fsunflower.setSelected(true);
        }
        
        if(tick5 == 1)
        {
            
            fbabybreath.setSelected(true);
        }
                
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fhydrangea = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        frose = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fsunflower = new javax.swing.JCheckBox();
        fbabybreath = new javax.swing.JCheckBox();
        MainMenuPkg = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        fblossom = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pick your bouquet:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 100, 190, 22);

        jLabel18.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel18.setText("to make our flower arrangements a true stunner!!");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(480, 80, 440, 30);

        jLabel19.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel19.setText("Our expert florists only use the most luxurious wrapping paper ");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(470, 50, 540, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("RM 45.00 ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 440, 100, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("RM 100.00");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(740, 440, 100, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("RM 80.00");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(440, 440, 100, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Blossom");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(130, 410, 90, 22);

        fhydrangea.setBackground(new java.awt.Color(255, 255, 204));
        fhydrangea.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fhydrangea.setText("Add to Wishlist");
        fhydrangea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fhydrangeaActionPerformed(evt);
            }
        });
        jPanel1.add(fhydrangea);
        fhydrangea.setBounds(440, 470, 150, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Hydrangea");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(440, 410, 110, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Roses");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(740, 410, 80, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Sunflower");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 830, 100, 22);

        frose.setBackground(new java.awt.Color(255, 255, 204));
        frose.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        frose.setText("Add to Wishlist");
        jPanel1.add(frose);
        frose.setBounds(740, 470, 150, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Baby breath");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 830, 120, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("RM 70.00");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(440, 860, 90, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("RM 85.00");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 860, 80, 22);

        fsunflower.setBackground(new java.awt.Color(255, 255, 204));
        fsunflower.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fsunflower.setText("Add to Wishlist");
        jPanel1.add(fsunflower);
        fsunflower.setBounds(130, 890, 150, 29);

        fbabybreath.setBackground(new java.awt.Color(255, 255, 204));
        fbabybreath.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fbabybreath.setText("Add to Wishlist");
        jPanel1.add(fbabybreath);
        fbabybreath.setBounds(440, 890, 150, 29);

        MainMenuPkg.setText("Continue Shopping");
        MainMenuPkg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuPkgActionPerformed(evt);
            }
        });
        jPanel1.add(MainMenuPkg);
        MainMenuPkg.setBounds(899, 930, 170, 29);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\java florist\\bbreath.jpeg")); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(440, 530, 220, 280);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/rose copy.png"))); // NOI18N
        jPanel1.add(jLabel23);
        jLabel23.setBounds(740, 120, 216, 280);

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel17.setText("*ALL PRICES ARE INCLUSIVE OF 6% GST");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(140, 950, 310, 20);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(740, 120, 220, 280);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/blossom copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(130, 120, 220, 280);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sunflower2 copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(130, 530, 220, 280);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/hydrangea copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(440, 120, 220, 280);

        fblossom.setBackground(new java.awt.Color(255, 255, 204));
        fblossom.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fblossom.setText("Add to Wishlist");
        fblossom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fblossomActionPerformed(evt);
            }
        });
        jPanel1.add(fblossom);
        fblossom.setBounds(130, 470, 150, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/header2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1100, 340);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/flower copy.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(810, 670, 290, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1122, 1036));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MainMenuPkgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuPkgActionPerformed
        // TODO add your handling code here:
        tick1=0;
        tick2=0;
        tick3=0;
        tick4=0;
        tick5=0;
        
        if(Bouquet.fblossom.isSelected())
        {
           bcount++;    
           tick1 = 1;
           //JOptionPane.showMessageDialog(null, tick1);
        }
           
        if(Bouquet.fhydrangea.isSelected())
        {
            bcount++;
            tick2 = 1;
        }
        if(Bouquet.frose.isSelected())
        {
            bcount++;
            tick3 = 1;
        }
        if(Bouquet.fsunflower.isSelected())
        {
            bcount++;
            tick4 = 1;
        }
        if(Bouquet.fbabybreath.isSelected())
        {
           bcount++;
           tick5 = 1;
        }
        
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainMenuPkgActionPerformed

    private void fblossomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fblossomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fblossomActionPerformed

    private void fhydrangeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fhydrangeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fhydrangeaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bouquet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bouquet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bouquet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bouquet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bouquet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainMenuPkg;
    public static javax.swing.JCheckBox fbabybreath;
    public static javax.swing.JCheckBox fblossom;
    public static javax.swing.JCheckBox fhydrangea;
    public static javax.swing.JCheckBox frose;
    public static javax.swing.JCheckBox fsunflower;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
