/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class Bulk extends javax.swing.JFrame {

    /**
     * Creates new form Bulk
     */
    public static int bkcount = 0;
    static int tick1;
    static int tick2;
    static int tick3;
    static int tick4;
    static int tick5;
    public Bulk() {
        initComponents();
        
        if(tick1 == 1)
        {
            
            faster.setSelected(true);
        }
        
        if(tick2 == 1)
        {
            
            fdahlia.setSelected(true);
        }
                
        if(tick3 == 1)
        {
            
            frose.setSelected(true);
        }  
        
        if(tick4 == 1)
        {
            
            fdaisy.setSelected(true);
        }
        
        if(tick5 == 1)
        {
            
            fsunflower.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fdahlia = new javax.swing.JCheckBox();
        faster = new javax.swing.JCheckBox();
        frose = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fdaisy = new javax.swing.JCheckBox();
        fsunflower = new javax.swing.JCheckBox();
        MainMenuBulk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pick your flower :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 110, 160, 32);

        fdahlia.setBackground(new java.awt.Color(204, 255, 204));
        fdahlia.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fdahlia.setText("Add to Wishlist");
        jPanel1.add(fdahlia);
        fdahlia.setBounds(480, 480, 160, 29);

        faster.setBackground(new java.awt.Color(204, 255, 204));
        faster.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        faster.setText("Add to Wishlist");
        jPanel1.add(faster);
        faster.setBounds(110, 480, 150, 29);

        frose.setBackground(new java.awt.Color(204, 255, 204));
        frose.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        frose.setText("Add to Wishlist");
        jPanel1.add(frose);
        frose.setBounds(840, 480, 160, 29);

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel6.setText("Happiness radiates like the fragrance from a flower and draws all good things from you.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 70, 740, 30);

        jLabel9.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel9.setText("We provide variety of beautiful and colourful flowers for your happiness.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(410, 100, 610, 30);

        fdaisy.setBackground(new java.awt.Color(204, 255, 204));
        fdaisy.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fdaisy.setText("Add to Wishlist");
        jPanel1.add(fdaisy);
        fdaisy.setBounds(110, 860, 150, 29);

        fsunflower.setBackground(new java.awt.Color(204, 255, 204));
        fsunflower.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fsunflower.setText("Add to Wishlist");
        jPanel1.add(fsunflower);
        fsunflower.setBounds(480, 860, 160, 29);

        MainMenuBulk.setText("Continue Shopping");
        MainMenuBulk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuBulkActionPerformed(evt);
            }
        });
        jPanel1.add(MainMenuBulk);
        MainMenuBulk.setBounds(890, 930, 180, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Aster");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 430, 51, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Dahlia");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 430, 70, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Rose");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(840, 430, 51, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Daisy");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 810, 51, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Sunflower");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 810, 100, 22);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/aster copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(110, 140, 220, 280);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/pink daisy copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(110, 520, 220, 280);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/rose copy_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(840, 140, 220, 280);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sunflower copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(480, 520, 220, 280);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/blue dahlia copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(480, 140, 220, 280);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("RM 4.50");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(480, 830, 80, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("RM 1.50");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(110, 450, 90, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("RM 4.00");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(480, 450, 90, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("RM 2.50");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(840, 450, 80, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("RM 4.00");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(110, 830, 80, 30);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/header2.png"))); // NOI18N
        jLabel19.setText("jLabel19");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(0, 0, 1100, 340);

        jLabel20.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel20.setText("*ALL PRICES ARE INCLUSIVE OF 6% GST");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(110, 930, 310, 20);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/flower copy.png"))); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(800, 680, 290, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1122, 1036));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MainMenuBulkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuBulkActionPerformed
        // TODO add your handling code here:
        tick1=0;
        tick2=0;
        tick3=0;
        tick4=0;
        tick5=0;
        if(Bulk.faster.isSelected())
        {
           bkcount++;    
           tick1 = 1;
        }
           
        if(Bulk.fdahlia.isSelected())
        {
            bkcount++;
            tick2 = 1;
        }
        if(Bulk.frose.isSelected())
        {
            bkcount++;
            tick3 = 1;
        }
        if(Bulk.fdaisy.isSelected())
        {
            bkcount++;
            tick4 = 1;
        }
        if(Bulk.fsunflower.isSelected())
        {
           bkcount++;
           tick5 = 1;
        }
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainMenuBulkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bulk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bulk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bulk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bulk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bulk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainMenuBulk;
    public static javax.swing.JCheckBox faster;
    public static javax.swing.JCheckBox fdahlia;
    public static javax.swing.JCheckBox fdaisy;
    public static javax.swing.JCheckBox frose;
    public static javax.swing.JCheckBox fsunflower;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    
}
