
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class DReview extends javax.swing.JFrame {

    /**
     * Creates new form DReview
     */
    public DReview() {
        initComponents();
    }
    //String e
     public DReview(String d, String a, String b, String j, String l, String p, String h, String g,String f, String u, String e, String tarikh, String s, String G) {
        initComponents();
        
       
        rcust_name.setText(d);
        rcust_address.setText(a);
        rcust_postcode.setText(b);
        rcuststate.setText(j);
        rcustphoneno.setText(l);
        rcustemail.setText(p);
        rr_name.setText(h);
        rr_address.setText(g);
        rr_postcode.setText(f);
        rr_state.setText(u);
        rtotal.setText(e);
        ddate1.setText(tarikh);
        rshipping.setText(s);
        rgrandtotal.setText(G);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rcust_name = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rcust_address = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        rcust_postcode = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        rcuststate = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rcustphoneno = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rcustemail = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rr_name = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        rr_address = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        rr_postcode = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        rtotal = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        rshipping = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        rgrandtotal = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        rr_state = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ddate1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Customer's details ");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(100, 100, 170, 32);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Name     :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(190, 150, 78, 32);

        rcust_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rcust_name);
        rcust_name.setBounds(300, 150, 414, 32);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Address  : ");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(190, 200, 90, 39);

        rcust_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rcust_address);
        rcust_address.setBounds(300, 200, 404, 80);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel32.setText("Postcode :");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(340, 660, 100, 30);

        rcust_postcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rcust_postcode);
        rcust_postcode.setBounds(390, 290, 117, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("State       :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(280, 340, 100, 20);

        rcuststate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rcuststate);
        rcuststate.setBounds(390, 340, 115, 28);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("Phone no :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(180, 390, 90, 34);

        rcustphoneno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rcustphoneno);
        rcustphoneno.setBounds(290, 400, 175, 34);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("Email       :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(180, 440, 90, 31);

        rcustemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rcustemail);
        rcustemail.setBounds(290, 440, 254, 31);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Post to ");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(110, 490, 110, 32);

        rr_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rr_name);
        rr_name.setBounds(350, 520, 346, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel23.setText("Receiver's name    :");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(180, 520, 160, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel24.setText("Receiver's address :");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(180, 560, 165, 29);

        rr_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rr_address);
        rr_address.setBounds(350, 560, 547, 70);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setText("State      :");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(340, 710, 80, 20);

        rr_postcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rr_postcode);
        rr_postcode.setBounds(440, 660, 157, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel27.setText("Total                :");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(180, 840, 137, 32);

        rtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rtotal);
        rtotal.setBounds(340, 840, 204, 32);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel28.setText("Postage charge :");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(180, 880, 160, 29);

        rshipping.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rshipping);
        rshipping.setBounds(340, 880, 207, 29);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel29.setText("Grand total        :");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(180, 910, 150, 38);

        rgrandtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rgrandtotal);
        rgrandtotal.setBounds(340, 910, 204, 38);

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        jPanel1.add(done);
        done.setBounds(960, 930, 69, 29);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel33.setText("Postcode :");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(280, 290, 90, 30);

        rr_state.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rr_state);
        rr_state.setBounds(440, 710, 200, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Delivery date      :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 750, 150, 20);

        ddate1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(ddate1);
        ddate1.setBounds(340, 750, 210, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/floral-header copy.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(250, 0, 600, 130);

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 0, 36)); // NOI18N
        jLabel4.setText("Receipt ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 30, 120, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/light pink background copy.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -10, 1100, 990);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1122, 1036));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank you for purchasing!! Have a wonderful day!");
        this.dispose();
    }//GEN-LAST:event_doneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DReview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel ddate1;
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rcust_address;
    public static javax.swing.JLabel rcust_name;
    private javax.swing.JLabel rcust_postcode;
    private javax.swing.JLabel rcustemail;
    private javax.swing.JLabel rcustphoneno;
    private javax.swing.JLabel rcuststate;
    private javax.swing.JLabel rgrandtotal;
    private javax.swing.JLabel rr_address;
    private javax.swing.JLabel rr_name;
    private javax.swing.JLabel rr_postcode;
    private javax.swing.JLabel rr_state;
    private javax.swing.JLabel rshipping;
    private javax.swing.JLabel rtotal;
    // End of variables declaration//GEN-END:variables
}
