
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class DShipping extends javax.swing.JFrame {

    /**
     * Creates new form DShipping
     */
 //public static float e;
    DateFormat df = DateFormat.getDateInstance();
    String tarikh = "";
    String tarikhpasti = " ";
    float ship_price = 0;
    public DShipping() {
        initComponents();
        
    }
    
    public DShipping(String e) {
        initComponents();
        ptotal.setText(e);
     
    }
    
 
    
    
    public String j;
    public void select_combo()
    {
        
        int ind = dcust_state.getSelectedIndex();
        if (ind == 0)
        {
            j = "Johor";
        }
        
         if (ind == 1)
        {
            j = "Kedah";
        }
         
          if (ind == 2)
        {
            j = "Kelantan";
        }
       
           if (ind == 3)
        {
            j = "Kuala Lumpur";
        }
           
            if (ind == 4)
        {
            j = "Labuan";
        }
            
             if (ind == 5)
        {
            j = "Melaka";
        }
             
              if (ind == 6)
        {
            j = "Negeri Sembilan";
        }
              
         if (ind == 7)
        {
            j = "Pahang";
        }      
         
          if (ind == 8)
        {
            j = "Perak";
        }
          
           if (ind == 9)
        {
            j = "Perlis";
        }
           
            if (ind == 10)
        {
            j = "Pulau Pinang";
        }
            
             if (ind ==11)
        {
            j = "Sabah";
        }
              if (ind == 12)
        {
            j = "Sarawak";
        }
               if (ind == 13)
        {
            j = "Selangor";
        }
                if (ind == 14)
        {
            j = "Terengganu";
        }
    }
    
     public String u;
        public void select_combo2()
    {
        
        int ind = r_state.getSelectedIndex();
        if (ind == 0)
        {
            u = "Johor";
        }
        
         if (ind == 1)
        {
            u = "Kedah";
        }
         
          if (ind == 2)
        {
            u = "Kelantan";
        }
       
           if (ind == 3)
        {
            u = "Kuala Lumpur";
        }
           
            if (ind == 4)
        {
            u = "Labuan";
        }
            
             if (ind == 5)
        {
            u = "Melaka";
        }
             
              if (ind == 6)
        {
            u = "Negeri Sembilan";
        }
              
         if (ind == 7)
        {
            u = "Pahang";
        }      
         
          if (ind == 8)
        {
            u = "Perak";
        }
          
           if (ind == 9)
        {
            u = "Perlis";
        }
           
            if (ind == 10)
        {
            u = "Pulau Pinang";
        }
            
             if (ind ==11)
        {
            u = "Sabah";
        }
              if (ind == 12)
        {
            u = "Sarawak";
        }
               if (ind == 13)
        {
            u = "Selangor";
        }
                if (ind == 14)
        {
            u = "Terengganu";
        }
    }
        
        public void shippingRate()
        {
            int ind = r_state.getSelectedIndex();
            if (ind == 4 || ind == 11 || ind == 12)
            {
                ship_price = (float) 26.5;
            }
            else
            {
                ship_price = 14;
            }
            pshipping.setText(ship_price + " ");
        }
        
        public void grandTotal()
        {
            int ind = r_state.getSelectedIndex();
            float o1;
            float grandtotal = 0;
            o1 = Float.parseFloat(ptotal.getText()); 
            if (ind == 4 || ind == 11 || ind == 12)
            {          
                grandtotal = (float) (o1 + 26.5);
            }
            else 
            {
                grandtotal = o1 + 14;
            }
            pgrandtotal.setText(grandtotal + " ");
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dcust_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dcust_address = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        dcust_postcode = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        dcust_state = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        dcust_phone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dcust_email2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        r_name = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        r_address = new javax.swing.JTextArea();
        jLabel39 = new javax.swing.JLabel();
        r_postcode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        r_state = new javax.swing.JComboBox<>();
        next1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ptotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pshipping = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pgrandtotal = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ddate = new com.toedter.calendar.JDateChooser();
        date_button = new javax.swing.JButton();
        display_date = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        combo_MM = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        combo_YYYY = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Customer's details ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 100, 170, 32);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Name     :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 150, 78, 32);

        dcust_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dcust_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcust_nameActionPerformed(evt);
            }
        });
        jPanel1.add(dcust_name);
        dcust_name.setBounds(280, 150, 425, 28);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Address  : ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(190, 200, 90, 39);

        dcust_address.setColumns(20);
        dcust_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dcust_address.setRows(5);
        jScrollPane2.setViewportView(dcust_address);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(280, 200, 421, 69);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel30.setText("Postcode   :");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(280, 290, 100, 30);

        dcust_postcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dcust_postcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcust_postcodeActionPerformed(evt);
            }
        });
        dcust_postcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dcust_postcodeKeyTyped(evt);
            }
        });
        jPanel1.add(dcust_postcode);
        dcust_postcode.setBounds(390, 290, 140, 28);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("State      :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(280, 340, 90, 30);

        dcust_state.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dcust_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Johor", "Kedah", "Kelantan", "Kuala Lumpur", "Labuan", "Melaka", "Negeri Sembilan", "Pahang", "Perak", "Perlis", "Pulau Pinang", "Sabah", "Sarawak", "Selangor", "Terengganu", " " }));
        jPanel1.add(dcust_state);
        dcust_state.setBounds(370, 340, 160, 28);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Phone no :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(180, 390, 90, 34);

        dcust_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dcust_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dcust_phoneKeyTyped(evt);
            }
        });
        jPanel1.add(dcust_phone);
        dcust_phone.setBounds(290, 400, 179, 28);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Email       :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(180, 440, 90, 31);

        dcust_email2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(dcust_email2);
        dcust_email2.setBounds(290, 440, 460, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Post to ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(110, 490, 110, 32);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Receiver's name    :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(180, 520, 170, 30);

        r_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_nameActionPerformed(evt);
            }
        });
        jPanel1.add(r_name);
        r_name.setBounds(350, 520, 400, 28);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Receiver's address :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(180, 560, 180, 29);

        r_address.setColumns(20);
        r_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r_address.setRows(5);
        jScrollPane1.setViewportView(r_address);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 560, 390, 80);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel39.setText("Postcode :");
        jPanel1.add(jLabel39);
        jLabel39.setBounds(340, 660, 90, 30);

        r_postcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r_postcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                r_postcodeKeyTyped(evt);
            }
        });
        jPanel1.add(r_postcode);
        r_postcode.setBounds(440, 660, 140, 28);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("State :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 710, 60, 20);

        r_state.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Johor", "Kedah", "Kelantan", "Kuala Lumpur", "Labuan", "Melaka", "Negeri Sembilan", "Pahang", "Perak", "Perlis", "Pulau Pinang", "Sabah", "Sarawak", "Selangor", "Terengganu", " " }));
        r_state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_stateActionPerformed(evt);
            }
        });
        jPanel1.add(r_state);
        r_state.setBounds(440, 710, 160, 28);

        next1.setText("Next");
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });
        jPanel1.add(next1);
        next1.setBounds(1020, 930, 65, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Total                :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 840, 130, 32);

        ptotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(ptotal);
        ptotal.setBounds(330, 840, 153, 32);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Postage charge :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 880, 150, 29);

        pshipping.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(pshipping);
        pshipping.setBounds(340, 880, 153, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Grand total        :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 910, 150, 38);

        pgrandtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(pgrandtotal);
        pgrandtotal.setBounds(340, 910, 153, 38);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel47.setText("Credit/Debit Card No  :");
        jPanel1.add(jLabel47);
        jLabel47.setBounds(180, 800, 210, 20);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(390, 800, 340, 28);

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 0, 36)); // NOI18N
        jLabel4.setText("Delivery ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 30, 140, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Delivery date");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 750, 140, 20);

        jLabel21.setText("MM              YYYY");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(870, 780, 140, 20);

        ddate.setBackground(new java.awt.Color(255, 204, 255));
        ddate.setDateFormatString("d MMM yyyy");
        jPanel1.add(ddate);
        ddate.setBounds(340, 750, 180, 26);

        date_button.setText("Date Confirmed");
        date_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(date_button);
        date_button.setBounds(580, 750, 150, 29);

        display_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(display_date);
        display_date.setBounds(750, 750, 170, 30);

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel6.setText("*Please fill in all the details*");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 70, 370, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/floral-header copy.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(250, 0, 540, 130);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Expiry date :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(740, 790, 120, 40);

        combo_MM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        combo_MM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(combo_MM);
        combo_MM.setBounds(850, 800, 60, 28);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("/");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(920, 790, 20, 40);

        combo_YYYY.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        combo_YYYY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027" }));
        jPanel1.add(combo_YYYY);
        combo_YYYY.setBounds(940, 800, 90, 26);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/light pink background copy.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(0, -10, 1100, 990);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1122, 1036));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dcust_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcust_nameActionPerformed
        // TODO add your handling code here:
        //a = dcust_name.getText();
    }//GEN-LAST:event_dcust_nameActionPerformed

    private void r_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_nameActionPerformed

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed
        // TODO add your handling code here:
      // SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
       String d = dcust_name.getText();      
       String a = dcust_address.getText();
       String b = dcust_postcode.getText();
       j="";
       select_combo();
       String l = dcust_phone.getText();
       String p = dcust_email2.getText();
       String h = r_name.getText();
       String g = r_address.getText();
       String f = r_postcode.getText();
       u="";
       select_combo2();
       String e = ptotal.getText();
       String t="";
        tarikh = display_date.getText();
        String s = pshipping.getText();
        String G = pgrandtotal.getText();
       new DReview(d,a,b,j,l,p,h,g,f,u,e, tarikh, s, G).setVisible(true);
    
       
       this.dispose();

    }//GEN-LAST:event_next1ActionPerformed

    private void dcust_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcust_phoneKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE ) || c==KeyEvent.VK_DELETE )
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_dcust_phoneKeyTyped

    private void dcust_postcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcust_postcodeKeyTyped
        // TODO add your handling code here
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE ) || c==KeyEvent.VK_DELETE )
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_dcust_postcodeKeyTyped

    private void r_postcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_r_postcodeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE ) || c==KeyEvent.VK_DELETE )
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_r_postcodeKeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE ) || c==KeyEvent.VK_DELETE )
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void date_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_buttonActionPerformed
        // TODO add your handling code here:
       //String tarikh = df.format(ddate.getDate());     
       tarikh = df.format(ddate.getDate()); 
       display_date.setText(tarikh);
       
    }//GEN-LAST:event_date_buttonActionPerformed

    private void r_stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_stateActionPerformed
        // TODO add your handling code here:
        shippingRate();
        grandTotal();
    }//GEN-LAST:event_r_stateActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void dcust_postcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcust_postcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcust_postcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DShipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DShipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DShipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DShipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DShipping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_MM;
    private javax.swing.JComboBox<String> combo_YYYY;
    private javax.swing.JButton date_button;
    private javax.swing.JTextArea dcust_address;
    private javax.swing.JTextField dcust_email2;
    public javax.swing.JTextField dcust_name;
    private javax.swing.JTextField dcust_phone;
    private javax.swing.JTextField dcust_postcode;
    private javax.swing.JComboBox<String> dcust_state;
    public static com.toedter.calendar.JDateChooser ddate;
    private javax.swing.JLabel display_date;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton next1;
    private javax.swing.JLabel pgrandtotal;
    private javax.swing.JLabel pshipping;
    private javax.swing.JLabel ptotal;
    private javax.swing.JTextArea r_address;
    private javax.swing.JTextField r_name;
    private javax.swing.JTextField r_postcode;
    private javax.swing.JComboBox<String> r_state;
    // End of variables declaration//GEN-END:variables
}
