/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    BuquetData[] bouquet = new BuquetData[5];
    PackageData[] pakej = new PackageData[5];
    BulkData[] bulk = new BulkData[5];
    FruitBasketData[] fruitbasket = new FruitBasketData[3];
    DShippingData lala = new DShippingData(); 
    
    
    
    public MainMenu() {
        initComponents();
        bouquet[0] = new BuquetData("Blossom", "RM 45.00");
        bouquet[1] = new BuquetData("Hydrangea", "RM 80.00");
        bouquet[2] = new BuquetData("Roses", "RM 100.00");
        bouquet[3] = new BuquetData("Sunflower", "RM 85.00");
        bouquet[4] = new BuquetData("Baby Breath", "RM 70.00");
        
        pakej[0] = new PackageData("Forever Love", "RM 150.00");
        pakej[1] = new PackageData("Congratulations", "RM 120.00");
        pakej[2] = new PackageData("Get Well Soon", "RM 90.00");
        pakej[3] = new PackageData("Condolescene, Sympathy", "RM 90.00");
        pakej[4] = new PackageData("Happy Birthday", "RM 135.00");
        
        bulk[0] = new BulkData("Aster", "RM 1.50");
        bulk[1] = new BulkData("Dahlia", "RM 4.00");
        bulk[2] = new BulkData("Rose", "RM 2.50");
        bulk[3] = new BulkData("Daisy", "RM 4.00");
        bulk[4] = new BulkData("Sunflower", "RM 4.50");
        
        fruitbasket[0] = new FruitBasketData("Small", "RM 50.00");
        fruitbasket[1] = new FruitBasketData("Medium", "RM 65.00");
        fruitbasket[2] = new FruitBasketData("Large", "RM 70.00");
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        hp1 = new javax.swing.JLabel();
        hp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ShopByCategory = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        M_Bouquet = new javax.swing.JMenuItem();
        M_Bulk = new javax.swing.JMenuItem();
        M_FruitBasket = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setText("Wishlist");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(980, 50, 87, 29);

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(980, 850, 71, 50);

        hp1.setFont(new java.awt.Font("Gigi", 3, 72)); // NOI18N
        hp1.setForeground(new java.awt.Color(102, 0, 51));
        hp1.setText("Happy Petals ");
        jPanel1.add(hp1);
        hp1.setBounds(350, 360, 475, 130);

        hp.setFont(new java.awt.Font("Gigi", 3, 72)); // NOI18N
        hp.setForeground(new java.awt.Color(102, 0, 51));
        hp.setText(" System");
        jPanel1.add(hp);
        hp.setBounds(440, 480, 330, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/frames floral.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 70, 780, 820);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/pine wood background copy.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1100, 960);

        ShopByCategory.setText("Menu");
        ShopByCategory.setFont(new java.awt.Font("Goudy Old Style", 0, 36)); // NOI18N
        ShopByCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShopByCategoryActionPerformed(evt);
            }
        });

        jMenu1.setText("Shop by Category");
        jMenu1.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N

        M_Bouquet.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        M_Bouquet.setText("Bouquet");
        M_Bouquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_BouquetActionPerformed(evt);
            }
        });
        jMenu1.add(M_Bouquet);

        M_Bulk.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        M_Bulk.setText("Bulk");
        M_Bulk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_BulkActionPerformed(evt);
            }
        });
        jMenu1.add(M_Bulk);

        M_FruitBasket.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        M_FruitBasket.setText("Fruit Basket");
        M_FruitBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_FruitBasketActionPerformed(evt);
            }
        });
        jMenu1.add(M_FruitBasket);

        jMenuItem3.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jMenuItem3.setText("Package");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        ShopByCategory.add(jMenu1);

        jMenuItem2.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jMenuItem2.setText("About Shop");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        ShopByCategory.add(jMenuItem2);

        jMenuBar1.add(ShopByCategory);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1122, 1065));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShopByCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShopByCategoryActionPerformed
        new Package().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_ShopByCategoryActionPerformed

    private void M_BouquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_BouquetActionPerformed
        // TODO add your handling code here:
        new Bouquet().setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_M_BouquetActionPerformed

    private void M_BulkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_BulkActionPerformed
        // TODO add your handling code here:
        new Bulk().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_M_BulkActionPerformed

    private void M_FruitBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_FruitBasketActionPerformed
        // TODO add your handling code here:
        new FruitBasket().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_M_FruitBasketActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Package().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Wishlist().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new AboutShop().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem M_Bouquet;
    private javax.swing.JMenuItem M_Bulk;
    private javax.swing.JMenuItem M_FruitBasket;
    private javax.swing.JMenu ShopByCategory;
    private javax.swing.JLabel hp;
    private javax.swing.JLabel hp1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    // End of variables declaration//GEN-END:variables
}
