


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class Package extends javax.swing.JFrame {

    /**
     * Creates new form Bouquet
     */
    public static int pcount = 0;
    static int tick1;
    static int tick2;
    static int tick3;
    static int tick4;
    static int tick5;
    public Package() {
        initComponents();
         if(tick1 == 1)
        {
            
            fforeverlove.setSelected(true);
        }
        
        if(tick2 == 1)
        {
            
            fcongratulations.setSelected(true);
        }
                
        if(tick3 == 1)
        {
            
            fgetwellsoon.setSelected(true);
        }  
        
        if(tick4 == 1)
        {
            
            fcondolescence.setSelected(true);
        }
        
        if(tick5 == 1)
        {
            
            fhappybirthday.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fforeverlove = new javax.swing.JCheckBox();
        fcongratulations = new javax.swing.JCheckBox();
        fgetwellsoon = new javax.swing.JCheckBox();
        fcondolescence = new javax.swing.JCheckBox();
        fhappybirthday = new javax.swing.JCheckBox();
        MainMenu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel23.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel23.setText("*ALL PRICES ARE INCLUSIVE OF 6% GST");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pick your package :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 160, 180, 34);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("RM 135.00");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 900, 90, 22);

        fforeverlove.setBackground(new java.awt.Color(255, 204, 255));
        fforeverlove.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fforeverlove.setText("Add to Wishlist");
        jPanel1.add(fforeverlove);
        fforeverlove.setBounds(90, 550, 160, 29);

        fcongratulations.setBackground(new java.awt.Color(255, 204, 255));
        fcongratulations.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fcongratulations.setText("Add to Wishlist");
        jPanel1.add(fcongratulations);
        fcongratulations.setBounds(420, 550, 160, 29);

        fgetwellsoon.setBackground(new java.awt.Color(255, 204, 255));
        fgetwellsoon.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fgetwellsoon.setText("Add to Wishlist");
        jPanel1.add(fgetwellsoon);
        fgetwellsoon.setBounds(750, 550, 150, 29);

        fcondolescence.setBackground(new java.awt.Color(255, 204, 255));
        fcondolescence.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fcondolescence.setText("Add to Wishlist");
        fcondolescence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcondolescenceActionPerformed(evt);
            }
        });
        jPanel1.add(fcondolescence);
        fcondolescence.setBounds(90, 930, 160, 29);

        fhappybirthday.setBackground(new java.awt.Color(255, 204, 255));
        fhappybirthday.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fhappybirthday.setText("Add to Wishlist");
        jPanel1.add(fhappybirthday);
        fhappybirthday.setBounds(420, 930, 160, 29);

        MainMenu.setText("Continue Shopping");
        MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuActionPerformed(evt);
            }
        });
        jPanel1.add(MainMenu);
        MainMenu.setBounds(902, 930, 167, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("RM 150.00");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 520, 100, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("RM 120.00");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 520, 90, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("RM 90.00");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(750, 520, 100, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("RM 90.00");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 900, 90, 22);

        jLabel2.setBackground(new java.awt.Color(255, 204, 255));
        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel2.setText("Happiness held is the seed.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(430, 70, 230, 30);

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel3.setText("Happiness shared is the flower. ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 100, 270, 30);

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel4.setText("Express your feelings with these lovely flowers.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 130, 390, 30);

        jLabel10.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel10.setText("We provide you with wonderful and gorgeous package. ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(320, 160, 460, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Forever love");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(90, 490, 120, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Congratulation");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(420, 490, 150, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Get Well Soon");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(750, 490, 130, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Condolescence, sympathy");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(90, 870, 240, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Happy Birthday");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(420, 870, 160, 22);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/congratulations copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(420, 200, 240, 280);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/get well soon copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(750, 200, 240, 280);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/condolences copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(90, 580, 240, 280);

        jPanel12.setBackground(new java.awt.Color(255, 204, 204));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/love copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel12);
        jPanel12.setBounds(90, 200, 240, 280);

        jPanel10.setBackground(new java.awt.Color(255, 204, 204));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/HB copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel10);
        jPanel10.setBounds(420, 590, 230, 280);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/header2.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(0, 0, 1100, 340);

        jLabel24.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel24.setText("*ALL PRICES ARE INCLUSIVE OF 6% GST");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(710, 610, 310, 20);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/flower copy.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(810, 690, 290, 240);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1122, 1036));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuActionPerformed
        // TODO add your handling code here:
        tick1=0;
        tick2=0;
        tick3=0;
        tick4=0;
        tick5=0;
        
        if(Package.fforeverlove.isSelected())
        {
           pcount++;
           tick1 = 1;
        }
        if(Package.fcongratulations.isSelected())
        {
           pcount++;
           tick2 = 1;
        }
        if(Package.fgetwellsoon.isSelected())
        {
           pcount++;
           tick3 = 1;
        }
        if(Package.fcondolescence.isSelected())
        {
           pcount++;
           tick4 = 1;
        }
        if(Package.fhappybirthday.isSelected())
        {
           pcount++;
           tick5 = 1;
        }
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainMenuActionPerformed

    private void fcondolescenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcondolescenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcondolescenceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Package().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainMenu;
    public static javax.swing.JCheckBox fcondolescence;
    public static javax.swing.JCheckBox fcongratulations;
    public static javax.swing.JCheckBox fforeverlove;
    public static javax.swing.JCheckBox fgetwellsoon;
    public static javax.swing.JCheckBox fhappybirthday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
