
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class WReview extends javax.swing.JFrame {

    /**
     * Creates new form WReview
     */
    public WReview() {
        initComponents();
    }

     public WReview(String d, String a, String b, String j, String l, String p,  String e, String tarikh) {
        initComponents();
        rcust_name.setText(d);
        rcust_address.setText(a);
        rcust_postcode.setText(b);
        rcust_state.setText(j);
        rcust_phoneno.setText(l);
        rcust_email.setText(p);
        rdate.setText(tarikh);
        rgrandtotal.setText(e);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rcust_name = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rcust_address = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        rcust_postcode = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        rcust_state = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rcust_phoneno = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rcust_email = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        rdate = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        rgrandtotal = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Customer's details ");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(30, 90, 190, 32);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Name     :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(120, 140, 78, 32);

        rcust_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rcust_name);
        rcust_name.setBounds(210, 140, 414, 32);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Address  : ");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(114, 200, 86, 39);

        rcust_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rcust_address);
        rcust_address.setBounds(210, 200, 404, 39);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel32.setText("Postcode :");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(200, 260, 90, 30);

        rcust_postcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rcust_postcode);
        rcust_postcode.setBounds(300, 260, 117, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("State       :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(200, 300, 90, 20);

        rcust_state.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rcust_state);
        rcust_state.setBounds(300, 300, 115, 28);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("Phone no :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(108, 360, 90, 34);

        rcust_phoneno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rcust_phoneno);
        rcust_phoneno.setBounds(210, 360, 175, 34);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("Email       :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(110, 410, 90, 31);

        rcust_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rcust_email);
        rcust_email.setBounds(210, 410, 254, 31);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Date pick up");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(50, 510, 140, 32);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setText("Date        :");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(150, 560, 90, 30);

        rdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rdate);
        rdate.setBounds(260, 560, 160, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel29.setText("Grand total        :");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(100, 630, 150, 38);

        rgrandtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(rgrandtotal);
        rgrandtotal.setBounds(260, 640, 200, 30);

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        jPanel1.add(done);
        done.setBounds(960, 930, 69, 29);

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 0, 36)); // NOI18N
        jLabel4.setText("Receipt ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 30, 110, 60);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/floral-header copy.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(250, 0, 600, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/abtract nude background copy.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 1100, 980);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1122, 1036));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank you for purchasing!! Have a wonderful day!");
        this.dispose();
    }//GEN-LAST:event_doneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WReview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rcust_address;
    private javax.swing.JLabel rcust_email;
    private javax.swing.JLabel rcust_name;
    private javax.swing.JLabel rcust_phoneno;
    private javax.swing.JLabel rcust_postcode;
    private javax.swing.JLabel rcust_state;
    public static javax.swing.JLabel rdate;
    private javax.swing.JLabel rgrandtotal;
    // End of variables declaration//GEN-END:variables
}
